/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meetings/{meeting_id}/consent-gate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consent Gate */
        get: operations["get_consent_gate_api_meetings__meeting_id__consent_gate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engagements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Engagement Endpoint */
        post: operations["create_engagement_endpoint_api_engagements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConsentGate
         * @description Result of evaluating whether a meeting may begin capture.
         *
         *     ``capture_may_begin`` is the single field a capture-start flow needs to
         *     check. ``prompt`` is populated only when the operator must confirm
         *     consent before capture is allowed to proceed.
         */
        ConsentGate: {
            status: components["schemas"]["ConsentGateStatus"];
            prompt?: components["schemas"]["ConsentPrompt"] | null;
        };
        /**
         * ConsentGateStatus
         * @description Where a given meeting sits relative to the consent gate.
         * @enum {string}
         */
        ConsentGateStatus: "not_required" | "awaiting_confirmation" | "confirmed";
        /**
         * ConsentPrompt
         * @description Operator-facing copy shown before capture begins (PRD L2).
         */
        ConsentPrompt: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Legal Basis */
            legal_basis: string;
        };
        /**
         * EngagementCreateRequest
         * @description Client background captured once, at engagement creation (PRD FR-3.1).
         */
        EngagementCreateRequest: {
            /** Client Organisation */
            client_organisation: string;
            /** Sector */
            sector: string;
            /** Commercial Context */
            commercial_context: string;
        };
        /** EngagementCreateResponse */
        EngagementCreateResponse: {
            /** Engagement Id */
            engagement_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_consent_gate_api_meetings__meeting_id__consent_gate_get: {
        parameters: {
            query: {
                engagement_id: string;
            };
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentGate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_engagement_endpoint_api_engagements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngagementCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
